### ISSUE TITLE
Mention field name or SSM parameter when it's required and cannot be found

### ISSUE THREAD

**Issue by qexpres** [ianlopshire/go-ssm-config#4]
When a parameter cannot be found in SSM you get a very simple error message: 
"ssmconfig: {} is required".

## Reproduction:
```Go
type Config struct {
    ReqParam string `ssm:"req-param" required:"true"`
}

func main() {
    if err := ssmconfig.Process("/config/path/", config); err != nil {
        log.Fatal(err.Error()) // returns "ssmconfig: {} is required" when /config/path/req-param is not set
    }
}
```

I would like to see a field name and/or the path to the SSM parameter that should be set, something like:
"ssmconfig: /config/path/req-param is required for ReqParam but could not be found"

**Comment by ianlopshire** [comment]
#5 should fix this until I have time to add better error handling in general.
